//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOS_ERP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class DEF_MENUS
    {
        [Key]
        public int ID { get; set; }
        public string menu_Description { get; set; }
        public Nullable<int> menu_Parent { get; set; }
        public string menu_Name { get; set; }
        public string menu_Type { get; set; }
        public string menu_status { get; set; }
        [NotMapped]
        public 
            List<DEF_MENUS> MenuList { get; set; }

        public List<DEF_MENUS> MenuTree(List<DEF_MENUS> menuList,int? parentid)
        {
            return menuList.Where(X => X.menu_Parent == parentid).Select(
                x => new DEF_MENUS
                {
                    ID = x.ID,
                    menu_Description = x.menu_Description,
                    menu_Parent = x.menu_Parent,
                    menu_Name = x.menu_Name,
                    menu_Type = x.menu_Type,
                    menu_status = x.menu_status
                }).ToList();
        }
    }
}
